### ISSUE TITLE
most efficient way to get PRs from GtiHub

### ISSUE THREAD

**Issue by rjbs** [fastmail/mint-tag#10]
https://github.com/fastmail/mint-tag/blob/78630bb5abb635ac51bf5acb059c8d4d66e7672a/lib/App/MintTag/Remote/Github.pm#L51-L59

I think that in fact you may want to use the /repos/:owner/:repo/pulls API end point, which has a ?state=open parameter.  This returns full pull requests, so the big question is whether you're better off:

1. fetching the list of issues with this label
2. performing N fetches, one per issue with PR

or

1. fetching all open PRs, filtering client-side by label
2. …and possibly performing more than one fetch, because of pagination

Page size can be set to 100, which seems likely to always be more than enough, reducing the query count from 1+N to 1.

**Comment by mmcclimon** [comment]
Fixed in f1e2c73e (oof).
