### ISSUE TITLE
compute next mint-tag s.n. schneller

### ISSUE THREAD

**Issue by rjbs** [fastmail/mint-tag#3]
https://github.com/fastmail/mint-tag/blob/429607872c6986289dfac28133ffb2e89a6043c3/lib/App/MintTag.pm#L193-L200

I think you're probably better off getting a prefix match first, up to and excluding the s.n., then picking the next s.n. available.  It'll run git-tag once instead of N times, and have the same number of races.  No?

**Comment by mmcclimon** [comment]
Oh yes, quite right. This was left from before I made the tag format more opinionated, so the serial number wasn't guaranteed to be the last hunk.
