### ISSUE TITLE
consider dropping Maybe[]

### ISSUE THREAD

**Issue by rjbs** [fastmail/mint-tag#6]
https://github.com/fastmail/mint-tag/blob/78630bb5abb635ac51bf5acb059c8d4d66e7672a/lib/App/MintTag/BuildStep.pm#L34-L39

Can we drop the Maybe[]?  You said it might've been added because of some kind of type system carping.  If we can ditch them, all the better.  Maybe[] is *usually* wrong compared to just leaving things unset.

**Comment by mmcclimon** [comment]
I have eliminated all of Types::Standard instead!
