### ISSUE TITLE
correct(?) capitalization of GitHub

### ISSUE THREAD

**Issue by rjbs** [fastmail/mint-tag#8]
https://github.com/fastmail/mint-tag/blob/78630bb5abb635ac51bf5acb059c8d4d66e7672a/lib/App/MintTag/Remote/Github.pm#L2-L3

You have made GitLab and Github, but GitHub seems to style themselves GitHub, with a big H.

Maybe this is fiddly, but we should probably match both brands or at least both files.  Sincerely, Rik from FastMail.

**Comment by mmcclimon** [comment]
ugh I swear I looked at this like 10 times and convinced myself it was all lowercase, but I think you're right.
